import { ISkillsMock } from './interface';
import Sprite from '../assets/images/icons/sprite.svg';

const SkillsMock: ISkillsMock[] = [
  {
    id: '00b6ff43-a9b5-4f2c-9d43-75ace12265c8',
    src: `${Sprite}#react`,
    alt: 'React',
    altRu: 'Реакт',
    description: 'React',
    descriptionRu: 'Реакт',
  },
  {
    id: 'b7148b70-85a4-4dd9-87e7-8fb6a3ef8bb8',
    src: `${Sprite}#redux`,
    alt: 'Redux',
    altRu: 'Редакс',
    description: 'Redux',
    descriptionRu: 'Редакс',
  },
  {
    id: '6a95f69b-ff81-4f52-a08e-6b28f7ad168e',
    src: `${Sprite}#typescript`,
    alt: 'TypeScript',
    altRu: 'ТайпСкрипт',
    description: 'TypeScript',
    descriptionRu: 'ТайпСкрипт',
  },
  {
    id: '88991854-22ab-4e97-9efa-e1a1bb9617b5',
    src: `${Sprite}#javascript`,
    alt: 'JavaScript',
    altRu: 'ДжаваСкрипт',
    description: 'JavaScript',
    descriptionRu: 'ДжаваСкрипт',
  },
  {
    id: 'd76a8256-4f9c-4690-a834-ad49ead700af',
    src: `${Sprite}#react`,
    alt: 'Cypress',
    altRu: 'Сайпресс',
    description: 'Cypress',
    descriptionRu: 'Сайпресс',
  },
  {
    id: '047f2984-0d24-4b8b-9c19-f62a590a4c84',
    src: `${Sprite}#scss`,
    alt: 'SASS / SCSS',
    altRu: 'SASS / SCSS',
    description: 'SASS / SCSS',
    descriptionRu: 'SASS / SCSS',
  },
  {
    id: 'adc23522-71f7-4e03-9dde-d32148c2afcc',
    src: `${Sprite}#css`,
    alt: 'CSS',
    altRu: 'CSS',
    description: 'CSS',
    descriptionRu: 'CSS',
  },
  {
    id: 'b256bb63-4723-42bc-8bda-4beb29f2d178',
    src: `${Sprite}#html`,
    alt: 'HTML',
    altRu: 'HTML',
    description: 'HTML',
    descriptionRu: 'HTML',
  },
  {
    id: 'f5e1fc61-f337-423b-9b2a-a562e2347c2e',
    src: `${Sprite}#git`,
    alt: 'Git / GitHub',
    altRu: 'Гит / ГитХаб',
    description: 'Git / GitHub',
    descriptionRu: 'Гит / ГитХаб',
  },
  {
    id: 'f2edaeee-a091-484b-9a0b-91dccf10cdd5',
    src: `${Sprite}#vscode`,
    alt: 'VS Code',
    altRu: 'VS Code',
    description: 'VS Code',
    descriptionRu: 'VS Code',
  },
  {
    id: '6432d40e-b721-4c68-89fd-16e5c7fca8d6',
    src: `${Sprite}#webpack`,
    alt: 'WebPack',
    altRu: 'ВебПак',
    description: 'WebPack',
    descriptionRu: 'ВебПак',
  },
  {
    id: 'aada8a1a-1c20-4a69-ae2e-121a14d1c74a',
    src: `${Sprite}#figma`,
    alt: 'Figma',
    altRu: 'Фигма',
    description: 'Figma',
    descriptionRu: 'Фигма',
  },
  {
    id: '4176c17d-aed0-49bf-8a66-120bc0c8ac48',
    src: `${Sprite}#photoshop`,
    alt: 'Photoshop',
    altRu: 'Фотошоп',
    description: 'Photoshop',
    descriptionRu: 'Фотошоп',
  },
];

export { SkillsMock };
